---

services:
  load_balancer:
    build:
      context: ./load_balancer
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: codecamp_password
