services:
  frontend:
    volumes:
      - "./frontend/src:/app/src"

  load_balancer:
    volumes:
      - "./load_balancer/nginx.conf:/etc/nginx/nginx.conf"

  api:
    volumes:
      - "./api/src:/app"
    stdin_open: true
    tty: true

  db:
    volumes:
      - "./db/data:/var/lib/postgresql/data"
